import AppKit
import ImageIO

/// Polls NSPasteboard.changeCount and reports new clipboard contents.
/// Note: on macOS 15+ the first actual content read triggers the system
/// pasteboard-privacy prompt — grant "Always Allow" once.
@MainActor
final class ClipboardWatcher {
    private var timer: Timer?
    private var lastCount: Int = NSPasteboard.general.changeCount
    private let onChange: @MainActor (ClipboardItem) -> Void

    init(onChange: @escaping @MainActor (ClipboardItem) -> Void) {
        self.onChange = onChange
    }

    func start() {
        let t = Timer(timeInterval: 0.4, repeats: true) { _ in
            Task { @MainActor in ClipboardWatcherRegistry.shared?.tick() }
        }
        RunLoop.main.add(t, forMode: .common)
        timer = t
        ClipboardWatcherRegistry.shared = self
    }

    /// Markers password managers and other tools set to say "this copy is not
    /// for you". Honouring them is the difference between a clipboard history
    /// and a thing that flashes your 1Password entry onto the notch mid-call.
    nonisolated static let secretTypes: [NSPasteboard.PasteboardType] = [
        .init("org.nspasteboard.ConcealedType"),
        .init("org.nspasteboard.TransientType"),
        .init("org.nspasteboard.AutoGeneratedType"),
    ]

    nonisolated static func isSecret(_ types: [NSPasteboard.PasteboardType]?) -> Bool {
        guard let types else { return false }
        return types.contains(where: secretTypes.contains)
    }

    /// What the pasteboard actually held, before any decoding — grabbed on the
    /// main thread (cheap), turned into a chip off it (not cheap).
    fileprivate enum Payload {
        case image(Data, NSPasteboard.PasteboardType)
        case files([URL])
        case text(String)
    }

    fileprivate func tick() {
        let pb = NSPasteboard.general
        guard pb.changeCount != lastCount else { return }
        lastCount = pb.changeCount
        guard let payload = Self.read(pb) else { return }
        let deliver = onChange
        DispatchQueue.global(qos: .userInitiated).async {
            guard let item = Self.item(from: payload) else { return }
            DispatchQueue.main.async { MainActor.assumeIsolated { deliver(item) } }
        }
    }

    private static func read(_ pb: NSPasteboard) -> Payload? {
        guard !isSecret(pb.types) else { return nil }
        for type in [NSPasteboard.PasteboardType.png, .tiff] {
            if let d = pb.data(forType: type) { return .image(d, type) }
        }
        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            return .files(urls)
        }
        if let s = pb.string(forType: .string) {
            let trimmed = s.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty else { return nil }
            return .text(trimmed)
        }
        return nil
    }

    /// Decoding a full-resolution screenshot, hashing it and rendering a
    /// thumbnail used to happen on the 0.4s main-thread timer — a multi-second
    /// stall exactly as the copy peek was supposed to animate in. ImageIO does
    /// the downsample in one pass and is safe off the main thread.
    /// Copy-back fidelity is worth some memory, but not unbounded memory: the
    /// strip holds ten items and a 6K screen grab arrives as ~80MB of
    /// uncompressed TIFF. Past these caps the chip keeps only its preview.
    nonisolated static let maxRetainedImageBytes = 8_000_000
    nonisolated static let maxRetainedTextLength = 128_000

    private static func item(from payload: Payload) -> ClipboardItem? {
        switch payload {
        case .image(let data, let type):
            guard let (cg, pxW, pxH) = downsample(data, maxDim: 320) else { return nil }
            let dims = "\(pxW)×\(pxH)"
            let thumb = NSImage(cgImage: cg, size: NSSize(width: cg.width, height: cg.height))
            let retained = data.count <= maxRetainedImageBytes ? data : nil
            return ClipboardItem(kind: .image, text: dims, image: thumb,
                                 signature: clipboardSignature(kind: .image, text: dims, data: data),
                                 imageData: retained, imageType: retained == nil ? "" : type.rawValue)
        case .files(let urls):
            let names = urls.map(\.lastPathComponent).joined(separator: ", ")
            return ClipboardItem(kind: .file, text: names, image: nil,
                                 signature: clipboardSignature(kind: .file, text: names, data: nil),
                                 fileURLs: urls)
        case .text(let trimmed):
            // The chip shows a preview; the full string is kept so copying it
            // back doesn't silently truncate what you copied.
            let text = String(trimmed.prefix(800))
            return ClipboardItem(kind: .text, text: text, image: nil,
                                 signature: clipboardSignature(kind: .text, text: text, data: nil),
                                 fullText: String(trimmed.prefix(maxRetainedTextLength)))
        }
    }

    /// Thumbnail plus the source's true pixel dimensions, in one decode.
    nonisolated static func downsample(_ data: Data, maxDim: CGFloat) -> (CGImage, Int, Int)? {
        guard let src = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let props = CGImageSourceCopyPropertiesAtIndex(src, 0, nil) as? [CFString: Any]
        let pxW = props?[kCGImagePropertyPixelWidth] as? Int ?? 0
        let pxH = props?[kCGImagePropertyPixelHeight] as? Int ?? 0
        let opts: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxDim,
        ]
        guard let cg = CGImageSourceCreateThumbnailAtIndex(src, 0, opts as CFDictionary) else { return nil }
        return (cg, pxW > 0 ? pxW : cg.width, pxH > 0 ? pxH : cg.height)
    }
}

/// Weak global so the timer closure doesn't retain the watcher.
@MainActor
private enum ClipboardWatcherRegistry {
    weak static var shared: ClipboardWatcher?
}
