import XCTest
@testable import AgentHUD

/// Aspect-morphing peek: the island takes the shape of what you copied.
final class FitSizeTests: XCTestCase {
    func testWideScreenshotStaysWide() {
        let s = hudFitSize(CGSize(width: 2800, height: 1000), in: CGSize(width: 210, height: 130))
        XCTAssertEqual(s.width, 210, accuracy: 0.5)
        XCTAssertEqual(s.height, 75, accuracy: 1)
        XCTAssertGreaterThan(s.width, s.height)
    }

    func testTallSnipStaysTall() {
        let s = hudFitSize(CGSize(width: 600, height: 900), in: CGSize(width: 210, height: 130))
        XCTAssertEqual(s.height, 130, accuracy: 0.5)
        XCTAssertGreaterThan(s.height, s.width)
    }

    func testSmallImageIsNotUpscaled() {
        let s = hudFitSize(CGSize(width: 80, height: 60), in: CGSize(width: 210, height: 130))
        XCTAssertEqual(s.width, 80, accuracy: 0.5)
        XCTAssertEqual(s.height, 60, accuracy: 0.5)
    }

    func testZeroSizedImageDoesNotCrashOrCollapse() {
        let s = hudFitSize(.zero, in: CGSize(width: 210, height: 130))
        XCTAssertGreaterThan(s.width, 0)
        XCTAssertGreaterThan(s.height, 0)
    }
}

/// The collapsed shape is the product's identity — it must stay exactly the
/// notch when idle, and never grow downward past the menu bar strip.
final class ContentSizeTests: XCTestCase {
    private let notch = NotchWindowController.Metrics(notchWidth: 200, notchHeight: 32, hasNotch: true)

    func testIdleCollapsedIsExactlyTheNotch() {
        let s = NotchWindowController.contentSize(for: .collapsed, metrics: notch,
                                                  aggregate: .info, sideBars: true)
        XCTAssertEqual(s.width, 200)
        XCTAssertEqual(s.height, 32, "idle HUD must be invisible inside the notch")
    }

    func testSideBarsWidenWithoutGrowingTaller() {
        let s = NotchWindowController.contentSize(for: .collapsed, metrics: notch,
                                                  aggregate: .running, sideBars: true)
        XCTAssertGreaterThan(s.width, 200, "side bars flank the notch")
        XCTAssertEqual(s.height, 32, "side bars must not hang below the notch")
    }

    func testBottomGlowGrowsSlightlyTallerInstead() {
        let s = NotchWindowController.contentSize(for: .collapsed, metrics: notch,
                                                  aggregate: .running, sideBars: false)
        XCTAssertEqual(s.width, 200)
        XCTAssertGreaterThan(s.height, 32)
        XCTAssertLessThanOrEqual(s.height, 40, "glow strip stays a thin lip")
    }

    func testPeekMorphsToTallPreview() {
        let plain = NotchWindowController.contentSize(for: .peek(.music(NowPlaying(app: "", title: "", artist: "", playing: true, artworkURL: ""))),
                                                      metrics: notch, aggregate: .info, sideBars: true)
        let tall = NotchWindowController.contentSize(for: .peek(.music(NowPlaying(app: "", title: "", artist: "", playing: true, artworkURL: ""))),
                                                     metrics: notch, aggregate: .info, sideBars: true,
                                                     peekPreview: CGSize(width: 87, height: 130))
        XCTAssertGreaterThan(tall.height, plain.height, "tall snips make a tall island")
    }
}

final class EventParsingTests: XCTestCase {
    func testEventFromJSON() {
        let e = AgentEvent.from(json: [
            "event": "done", "host": "box", "project": "repo",
            "session_id": "s1", "session_name": "my session", "message": " hi ",
        ])
        XCTAssertEqual(e?.kind, .done)
        XCTAssertEqual(e?.message, "hi", "messages are trimmed")
        XCTAssertEqual(e?.sessionName, "my session")
    }

    func testUnknownEventKindIsRejected() {
        XCTAssertNil(AgentEvent.from(json: ["event": "explode"]))
        XCTAssertNil(AgentEvent.from(json: [:]))
    }

    func testSessionLabelPrefersNameThenProject() {
        let named = AgentEvent(kind: .done, host: "h", project: "proj", sessionId: "1",
                               sessionName: "Nice Name", message: "", hook: "", image: nil, ts: Date())
        XCTAssertTrue(named.label.contains("Nice Name"))
        let unnamed = AgentEvent(kind: .done, host: "h", project: "proj", sessionId: "1",
                                 sessionName: "", message: "", hook: "", image: nil, ts: Date())
        XCTAssertTrue(unnamed.label.contains("proj"))
    }

    /// Claude Code regenerates "<user>-<2 hex>" names on resume even when the
    /// session was named; those must fall back to the project folder.
    func testAutoGeneratedNameFallsBackToProject() {
        let auto = "\(NSUserName().replacingOccurrences(of: ".", with: "-"))-d4"
        XCTAssertEqual(sessionDisplayName(auto, project: "botim-cs-email-agent"), "botim-cs-email-agent")
        XCTAssertEqual(sessionDisplayName("BIG-BRAIN", project: "anything"), "BIG-BRAIN")
    }
}

final class HTTPParsingTests: XCTestCase {
    func testParsesPostWithBody() {
        let raw = "POST /event HTTP/1.1\r\nContent-Type: application/json\r\nContent-Length: 7\r\n\r\n{\"a\":1}"
        let req = EventServer.parseRequest(Data(raw.utf8))
        XCTAssertEqual(req?.method, "POST")
        XCTAssertEqual(req?.path, "/event")
        XCTAssertEqual(req.map { String(decoding: $0.body, as: UTF8.self) }, "{\"a\":1}")
    }

    func testWaitsForIncompleteBody() {
        let raw = "POST /event HTTP/1.1\r\nContent-Length: 20\r\n\r\n{\"a\":1}"
        XCTAssertNil(EventServer.parseRequest(Data(raw.utf8)), "must wait for the rest of the body")
    }

    func testWaitsForIncompleteHeaders() {
        XCTAssertNil(EventServer.parseRequest(Data("GET /health HT".utf8)))
    }

    func testParsesGetWithoutBody() {
        let req = EventServer.parseRequest(Data("GET /health HTTP/1.1\r\n\r\n".utf8))
        XCTAssertEqual(req?.method, "GET")
        XCTAssertEqual(req?.path, "/health")
    }
}

final class SessionModelTests: XCTestCase {
    private func session(ctx: Int) -> SessionInfo {
        SessionInfo(id: "1", host: "h", project: "p", sessionName: "n",
                    kind: .running, message: "", updated: Date(), ctxUsed: ctx)
    }

    func testStandardContextWindow() {
        let s = session(ctx: 100_000)
        XCTAssertEqual(s.effectiveCtxLimit, 200_000)
        XCTAssertEqual(s.ctxFraction ?? 0, 0.5, accuracy: 0.01)
    }

    /// [1m] sessions blow past 200k; the bar must not pin at 100%.
    func testLargeContextWindowIsInferred() {
        let s = session(ctx: 337_000)
        XCTAssertEqual(s.effectiveCtxLimit, 1_000_000)
        XCTAssertLessThan(s.ctxFraction ?? 1, 0.5)
    }

    func testNoUsageYieldsNoFraction() {
        XCTAssertNil(session(ctx: 0).ctxFraction)
    }
}
