import XCTest
import AppKit
@testable import AgentHUD

/// The listener is reachable by any local process, by every account on an
/// SSH-tunnelled box, and — before the origin gate — by any website you
/// happened to have open. These are the ways that went wrong.
final class ServerHardeningTests: XCTestCase {
    func testNegativeContentLengthIsRejectedNotFatal() {
        // `Content-Length: -1` used to pass the body-size guard and then trap
        // inside prefix(), killing the app from one line of netcat.
        let raw = "POST /event HTTP/1.1\r\nContent-Length: -1\r\n\r\n"
        let req = EventServer.parseRequest(Data(raw.utf8))
        XCTAssertEqual(req?.body.count, 0)
        XCTAssertEqual(req?.method, "POST")
    }

    func testGarbageContentLengthReadsAsZero() {
        let raw = "POST /event HTTP/1.1\r\nContent-Length: banana\r\n\r\n"
        XCTAssertEqual(EventServer.parseRequest(Data(raw.utf8))?.body.count, 0)
    }

    func testOriginIsParsed() {
        let raw = "POST /event HTTP/1.1\r\nOrigin: https://evil.example\r\nContent-Length: 0\r\n\r\n"
        XCTAssertEqual(EventServer.parseRequest(Data(raw.utf8))?.origin, "https://evil.example")
    }

    /// Hooks, curl and the reporter send no Origin at all; browsers always do.
    func testLocalClientsWithoutAnOriginAreAllowed() {
        XCTAssertTrue(EventServer.isAllowedOrigin(nil))
        XCTAssertTrue(EventServer.isAllowedOrigin(""))
    }

    func testExtensionOriginsAreAllowed() {
        XCTAssertTrue(EventServer.isAllowedOrigin("chrome-extension://abcdef"))
        XCTAssertTrue(EventServer.isAllowedOrigin("safari-web-extension://abcdef"))
        XCTAssertTrue(EventServer.isAllowedOrigin("moz-extension://abcdef"))
    }

    /// The drive-by case: a page you have open POSTing to 127.0.0.1.
    func testWebsiteOriginsAreRefused() {
        XCTAssertFalse(EventServer.isAllowedOrigin("https://evil.example"))
        XCTAssertFalse(EventServer.isAllowedOrigin("http://localhost:3000"))
        XCTAssertFalse(EventServer.isAllowedOrigin("null"))
    }
}

/// `image_path` decides which file the HUD opens, from an unauthenticated
/// request body.
final class ImagePathTests: XCTestCase {
    func testNonImageExtensionsAreRefused() {
        XCTAssertNil(safeImagePath("~/.ssh/id_rsa"))
        XCTAssertNil(safeImagePath("/etc/passwd"))
    }

    func testMissingFileIsRefused() {
        XCTAssertNil(safeImagePath("/tmp/definitely-not-here-\(UUID().uuidString).png"))
    }

    func testRealImageIsAccepted() throws {
        let url = URL(fileURLWithPath: NSTemporaryDirectory())
            .appendingPathComponent("agent-hud-test-\(UUID().uuidString).png")
        let img = NSImage(size: NSSize(width: 4, height: 4))
        img.lockFocus()
        NSColor.red.drawSwatch(in: NSRect(x: 0, y: 0, width: 4, height: 4))
        img.unlockFocus()
        let tiff = try XCTUnwrap(img.tiffRepresentation)
        let png = try XCTUnwrap(NSBitmapImageRep(data: tiff)?.representation(using: .png, properties: [:]))
        try png.write(to: url)
        defer { try? FileManager.default.removeItem(at: url) }
        XCTAssertEqual(safeImagePath(url.path), url.path)
    }
}

/// Password managers mark their copies; a clipboard history that ignores the
/// marker flashes your credentials onto the notch.
final class ClipboardPrivacyTests: XCTestCase {
    func testConcealedContentIsSkipped() {
        XCTAssertTrue(ClipboardWatcher.isSecret([.init("org.nspasteboard.ConcealedType")]))
        XCTAssertTrue(ClipboardWatcher.isSecret([.string, .init("org.nspasteboard.TransientType")]))
        XCTAssertTrue(ClipboardWatcher.isSecret([.init("org.nspasteboard.AutoGeneratedType")]))
    }

    func testOrdinaryContentIsKept() {
        XCTAssertFalse(ClipboardWatcher.isSecret([.string]))
        XCTAssertFalse(ClipboardWatcher.isSecret([.png, .tiff]))
        XCTAssertFalse(ClipboardWatcher.isSecret(nil))
    }

    /// A chip must copy back the original, not the 800-char preview.
    func testFullTextSurvivesForCopyBack() {
        let long = String(repeating: "x", count: 2000)
        let item = ClipboardItem(kind: .text, text: String(long.prefix(800)), image: nil,
                                 signature: "t:preview", fullText: long)
        XCTAssertEqual(item.text.count, 800, "the chip still shows a preview")
        XCTAssertEqual(item.fullText.count, 2000, "copying it back must not truncate")
    }
}

/// A stray byte in path data used to hang the render thread outright.
final class SVGPathRobustnessTests: XCTestCase {
    func testTrailingGarbageAfterCloseDoesNotHang() {
        // Z consumes nothing, so the index parked and closeSubpath() ran
        // forever. Reaching the assertion at all is the test.
        _ = SVGPath.parse("M0 0 L10 10 Z5")
        _ = SVGPath.parse("M0 0 L10 10 Z.")
        _ = SVGPath.parse("m0 0 l10 10 z5")
        XCTAssertTrue(true, "parse returned instead of spinning")
    }

    /// Letters whose uppercase form is more than one character ("ß" → "SS")
    /// trapped in Character(_:) instead of hitting the unknown-command bail.
    func testMultiCharacterUppercaseLetterDoesNotCrash() {
        _ = SVGPath.parse("M0 0 \u{00DF}10 10")
        _ = SVGPath.parse("M0 0 \u{FB01}5 5")
        XCTAssertTrue(true, "unknown commands bail out rather than trapping")
    }

    func testRealPathsStillParse() {
        XCTAssertFalse(SVGPath.parse(BrandPaths.claude).isEmpty)
        XCTAssertFalse(SVGPath.parse("M0 0 L10 0 L10 10 Z").isEmpty)
    }
}

@MainActor
final class AttentionCountingTests: XCTestCase {
    private func event(_ kind: EventKind, sid: String) -> AgentEvent {
        AgentEvent(kind: kind, host: "box", project: "p", sessionId: sid,
                   sessionName: "n", message: "m", hook: "t", image: nil, ts: Date())
    }

    /// Two permission prompts in one turn is routine, and the decrement only
    /// ever ran on a transition — so the residue left the notch glowing
    /// orange after everything had finished.
    func testRepeatedAttentionForOneSessionCountsOnce() {
        let s = AppState()
        s.apply(event(.attention, sid: "S"))
        s.apply(event(.attention, sid: "S"))
        s.apply(event(.attention, sid: "S"))
        XCTAssertEqual(s.pendingAttention, 1, "one waiting session is one pending item")
        s.apply(event(.done, sid: "S"))
        XCTAssertEqual(s.pendingAttention, 0, "answering it must clear the glow")
        XCTAssertEqual(s.aggregate, .done)
    }

    func testSeveralWaitingSessionsStillCountSeparately() {
        let s = AppState()
        s.apply(event(.attention, sid: "A"))
        s.apply(event(.attention, sid: "B"))
        XCTAssertEqual(s.pendingAttention, 2)
        s.apply(event(.done, sid: "A"))
        XCTAssertEqual(s.pendingAttention, 1)
    }

    /// The 12-card cap dropped cards without handing back what they held, so
    /// an evicted attention card leaked its count permanently.
    func testEvictedCardsReleaseTheirPendingCount() {
        let s = AppState()
        for i in 0..<20 { s.apply(event(.attention, sid: "S\(i)")) }
        XCTAssertLessThanOrEqual(s.sessions.count, 12)
        XCTAssertEqual(s.pendingAttention, s.sessions.filter { $0.kind == .attention }.count,
                       "the counter must match what is actually on screen")
    }
}
